### ISSUE TITLE
Why is sendMidiMessage private?

### ISSUE THREAD

**Issue by sinosoidal** [kshoji/USB-MIDI-Driver#27]
Hi,

First of all I would like to give you my props for this work. 

I would like to ask you something. I understand that you wanted to provide a complete API for the most diverse type of midi messages, but, why keep sendMidiMessage private? If this was public, one could send midi straight ahead with cases, just by filling the parameters.

    public void sendMidiMessage(int codeIndexNumber, int cable, int byte1, int byte2, int byte3);

I have been using RtMidi on desktop and PGMidi for iOS and they all make use of send midi with just three parameters. I think this freedom would greatly enhance the usability of the API.

By the way, what is cable? I can't figure it out. Can you explain me?

Thanks,

Regards,

Nuno Santos

**Comment by kshoji** [comment]
OK, I understand that the method with 3 bytes arguments makes convenient to send various MIDI messages.
I'll add a public method with suitable documents.

The method signature will be like this:
```java
public void sendMidiMessage(int cable, int byte1, int byte2, int byte3)
```

The `cable` is the virtual cable ID for USB MIDI device.
An USB MIDI device can have 16 cables to supply different functions.
For example, cable ID 0 is a synthesizer, ID 1 is a sequencer, ID 2 is an effector, ...
It's described at USB MIDI specification(PDF). At 16 page, `4 USB-MIDI Event Packets`.
http://www.usb.org/developers/docs/devclass_docs/midi10.pdf

Regards,
Kaoru Shoji
