### ISSUE TITLE
Conficts occured  after the lib and samples imported into Eclipse

### ISSUE THREAD

**Issue by haogg** [kshoji/USB-MIDI-Driver#32]
the conflicts shows that the Class -- MidiMessage and SysexMessage occure twice..
it lead to that i can not compile the sample.
So,does this means that this is not a complete or full upgrade?

**Comment by kshoji** [comment]
Sorry, the master branch's code has been crashed since last release.
I've removed unnecessary codes.

**Comment by haogg** [comment]
hi kshouji. I also did that you did，and  sample worked on phone。

**Comment by haogg** [comment]
I feel USB-MIDI-Driver has a bug that comes from Android itself：If i use USB-MIDI-Driver and SoundPool in one project。 If i plug out the usb out，the the phone will be stuck for several  seconds to  make sound。It is really confusing. Test Device: Xiaomi 4.
