### ISSUE TITLE
Using raw source code -> Error

### ISSUE THREAD

**Issue by PatrickWinkler** [kshoji/USB-MIDI-Driver#34]
Hello,
I downloaded the project and copied the driver into a new Android-Project (Eclipse Luna),
like it is described in the wiki.

When i try to build the MIDIDriver I get a long list of errors.

Description	Resource	Path	Location	Type
The method onDeviceAttached(UsbDevice) from the type OnMidiDeviceAttachedListener is deprecated	MidiDeviceConnectionWatcher.java	/MIDIDriver/src/jp/kshoji/driver/midi/device	line 181	Java Problem
The method onDeviceDetached(UsbDevice) from the type OnMidiDeviceDetachedListener is deprecated	MidiDeviceConnectionWatcher.java	/MIDIDriver/src/jp/kshoji/driver/midi/device	line 70	Java Problem
LOLLIPOP cannot be resolved or is not a field	UsbMidiDeviceUtils.java	/MIDIDriver/src/jp/kshoji/driver/midi/util	line 190	Java Problem
LOLLIPOP cannot be resolved or is not a field	UsbMidiDeviceUtils.java	/MIDIDriver/src/jp/kshoji/driver/midi/util	line 219	Java Problem
The method getManufacturerName() is undefined for the type UsbDevice	UsbMidiDeviceUtils.java	/MIDIDriver/src/jp/kshoji/driver/midi/util	line 220	Java Problem
The method getProductName() is undefined for the type UsbDevice	UsbMidiDeviceUtils.java	/MIDIDriver/src/jp/kshoji/driver/midi/util	line 191	Java Problem
InvalidMidiDataException cannot be resolved to a type	MidiMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 16	Java Problem
InvalidMidiDataException cannot be resolved to a type	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 30	Java Problem
InvalidMidiDataException cannot be resolved to a type	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 40	Java Problem
InvalidMidiDataException cannot be resolved to a type	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 43	Java Problem
InvalidMidiDataException cannot be resolved to a type	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 56	Java Problem
InvalidMidiDataException cannot be resolved to a type	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 58	Java Problem
MidiSystem cannot be resolved	UsbMidiSystem.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 81	Java Problem
MidiSystem cannot be resolved	UsbMidiSystem.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 85	Java Problem
MidiSystem cannot be resolved	UsbMidiSystem.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 96	Java Problem
MidiSystem cannot be resolved	UsbMidiSystem.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 100	Java Problem
MidiSystem cannot be resolved	UsbMidiSystem.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 123	Java Problem
MidiSystem cannot be resolved	UsbMidiSystem.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 141	Java Problem
ShortMessage cannot be resolved to a variable	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 13	Java Problem
ShortMessage cannot be resolved to a variable	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 13	Java Problem
ShortMessage cannot be resolved to a variable	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 42	Java Problem
ShortMessage cannot be resolved to a variable	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 42	Java Problem
ShortMessage cannot be resolved to a variable	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 57	Java Problem
ShortMessage cannot be resolved to a variable	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 57	Java Problem
The method setMessage(byte[], int) from the type MidiMessage refers to the missing type InvalidMidiDataException	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 45	Java Problem
The method setMessage(byte[], int) from the type SysexMessage refers to the missing type InvalidMidiDataException	SysexMessage.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi	line 32	Java Problem
Info cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 65	Java Problem
Info cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 79	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 81	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 94	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 107	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 120	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 133	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 146	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 159	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 172	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 185	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 198	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 211	Java Problem
InvalidMidiDataException cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 224	Java Problem
MetaMessage cannot be resolved to a type	UsbMidiReceiver.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 46	Java Problem
MetaMessage cannot be resolved to a type	UsbMidiReceiver.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 47	Java Problem
MetaMessage cannot be resolved to a type	UsbMidiReceiver.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 47	Java Problem
MidiDevice cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 28	Java Problem
MidiDevice cannot be resolved to a type	UsbMidiReceiver.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 112	Java Problem
MidiDevice cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 69	Java Problem
MidiDeviceReceiver cannot be resolved to a type	UsbMidiReceiver.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 20	Java Problem
MidiDeviceTransmitter cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 23	Java Problem
MidiUnavailableException cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 58	Java Problem
MidiUnavailableException cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 86	Java Problem
MidiUnavailableException cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 149	Java Problem
MidiUnavailableException cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 169	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 30	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 30	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 47	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 73	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 91	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 91	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 118	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 118	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 121	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 139	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 149	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 150	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 150	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 160	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 161	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 161	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 162	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 228	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 230	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 241	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 242	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 242	Java Problem
Receiver cannot be resolved to a type	UsbMidiDevice.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 254	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 27	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 43	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 44	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 49	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 50	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 76	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 80	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 89	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 93	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 102	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 106	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 115	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 119	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 128	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 132	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 141	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 145	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 154	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 158	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 167	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 171	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 180	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 184	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 193	Java Problem
Receiver cannot be resolved to a type	UsbMidiTransmitter.java	/MIDIDriver/src/jp/kshoji/javax/sound/midi/usb	line 197	Java Problem

**Comment by kshoji** [comment]
The maven build had been crashed since very former commit.
I fixed this issue at cb6a652eb8c2e16080092498f837bee95d522118, and added build script for Travis CI.
