### ISSUE TITLE
OnMidiInputEventListenerImpl take interpret wrongly about single byte messages

### ISSUE THREAD

**Issue by trrk** [kshoji/USB-MIDI-Driver#47]
`OnMidiInputEventListenerImpl.onMidiSingleByte()`にSysEX以外の1バイトのメッセージ(Active sensing,Timing clockなど)が渡されると、正しく解釈されずエラーが起きますので報告です。

対応など、よろしくお願いします。

**Comment by kshoji** [comment]
SysexMessageをnewしていましたが、ShortMessageの間違いのようでした。

**Comment by trrk** [comment]
そうだったのですね。
ありがとうございました。

**Comment by kshoji** [comment]
コミット 9df7384023849b44fcd95b378a3f21ad8d14a9a0 で修正しました。
