### ISSUE TITLE
trying to send this sysex message for example

### ISSUE THREAD

**Issue by deliad2** [kshoji/USB-MIDI-Driver#49]
hi, this is the sysex message i'm trying to send using MidiSystemExclusive, 

found a bug that sysex over 3 bytes isn't transferred 

F0 7F 7F 04 04 00 3F F7 

this is a 8 bytes sysex , and i think you don't cover it under your code, am i correct

however, with this one, 3 bytes message ,i can send and see it comes on my computer midi in
F0 7F F7

seems that the api is limited for maximum 3 bytes message, which is not good, need to fix
thanks for helping

**Comment by kshoji** [comment]
This may be the same reason for the issue #40. This issue #40 is written about receiving only, but transfer is also affected.
I've confirmed the issue with the older code.
With the latest release of the library, the sysex message is transferred correctly.

Regards,
Kaoru
