### ISSUE TITLE
Audio stops when USB midi device is connected

### ISSUE THREAD

**Issue by sinosoidal** [kshoji/USB-MIDI-Driver#54]
I'm building a synthesiser app and I'm having an issue while integratin USB-MIDI-Driver. As soon as I plug the midi device, the audio stops. 

The midi devices are detected and the midi signal comes in, but no audio comes out after that moment. 

Is this a know issue? Am I missing something?

**Comment by sinosoidal** [comment]
I have just realised this is a know issue.

**Comment by michaelknoch** [comment]
have you found a workaround @sinosoidal ?
