### ISSUE TITLE
Some vendor ids are wrong in device_filter.xml

### ISSUE THREAD

**Issue by acleu** [kshoji/USB-MIDI-Driver#59]
I don't use your library myself (I have my own library for that), but since I saw your values in various apps ...

According to http://www.linux-usb.org/usb.ids:
- 0944 is the hex value for Korg. It must be converted to decimal: 2372
- CME has value 0x7104, decimal 28932. I could not find the id 9615.
- 5840/16d0 is the value for MCS. According to https://usb-ids.gowdy.us/read/UD/16d0, they apparently sell PIDs, see also http://www.mcselec.com/index.php?page=shop.product_details&product_id=92&option=com_phpshop

**Comment by kshoji** [comment]
I fixed the issue, and merged into develop branch. thanks.
