### ISSUE TITLE
Library not working when targeting Android 34

### ISSUE THREAD

**Issue by stephanedupont** [kshoji/USB-MIDI-Driver#81]
The library seems to not working if we target Android 34. Work fine (even on Android 34) if targeting Android 33.

I'm trying to diagnose this, but maybe this is a known issue?

**Comment by kshoji** [comment]
This issue is likely to be resolved with #80.
I'll merge it after checking.

**Comment by kshoji** [comment]
It also seems to need #79.

**Comment by stephanedupont** [comment]
Thank you, using the develop branch and it works great now :)
