### ISSUE TITLE
Android 14 crash

### ISSUE THREAD

**Issue by AnSmulie** [kshoji/USB-MIDI-Driver#84]
We recently update to Target SDK Android 34 per Google request and is facing surging crashes with this plugin. We really need your help on resolving this quickly. Also would there be any support for future Android 14 issues like this?

![Screenshot 2024-07-19 172750](https://github.com/user-attachments/assets/93d4b6ad-1757-4190-b2db-99d7d466e2b6)

**Comment by peterdk** [comment]
I encountered the same issue. It can be fixed by adding `.setPackage(context.getPackageName())` to the Intent, and make sure to add ` Context.RECEIVER_EXPORTED` on Android 34+. (In `MidiDeviceConnectionWatcher`)


```
 synchronized (deviceGrantQueue) {
                    if (!deviceGrantQueue.isEmpty() && !isGranting) {
                        isGranting = true;
                        grantingDevice = deviceGrantQueue.remove();
                        PendingIntent permissionIntent = PendingIntent.getBroadcast(
                                context, 0, new Intent(UsbMidiGrantedReceiver.USB_PERMISSION_GRANTED_ACTION).setPackage(context.getPackageName()),
                                android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S ? PendingIntent.FLAG_MUTABLE : 0
                        );

                        if (Build.VERSION.SDK_INT >= 34)
                        {
                            context.registerReceiver(new UsbMidiGrantedReceiver(grantingDevice, deviceAttachedListener), new IntentFilter(UsbMidiGrantedReceiver.USB_PERMISSION_GRANTED_ACTION), Context.RECEIVER_EXPORTED);
                        }else {
                            context.registerReceiver(new UsbMidiGrantedReceiver(grantingDevice, deviceAttachedListener), new IntentFilter(UsbMidiGrantedReceiver.USB_PERMISSION_GRANTED_ACTION));
                        }
                        usbManager.requestPermission(grantingDevice, permissionIntent);
                    }
                }
```

**Comment by peterdk** [comment]
Not sure if that aligns with current code, I have a customized version of the code. But this works on my Android 14 device with a USB midi device.

**Comment by peterdk** [comment]
Although I would advice to use the Android build-in `MidiManager` support for anything new. Cause this library is only really needed for really old MIDI devices that do not adhere to normal USB MIDI standards.

**Comment by AnSmulie** [comment]
Thank you @peterdk ! It seems like the RECEIVER_EXPORTED context is the one causing problem on Android 14. We have updated the plugin to the newest version and everything seems to work fine now.
